# Generated by Django 4.2.7 on 2023-12-11 23:33

from django.db import migrations, models
import userprofiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=userprofiles.models.upload_to, null=True, upload_to=userprofiles.models.upload_to),
        ),
    ]
