version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - type: bind
        source: ./frontend
        target: /app

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"