version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: insta_clone_postgres
    environment:
      POSTGRES_USER: insta_clone
      POSTGRES_PASSWORD: insta_clone
      POSTGRES_DB: insta_clone
    ports:
      - "5435:5432"
    volumes:
      - insta-clone-postgres:/var/lib/postgresql/data

volumes:
  insta-clone-postgres:
